### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by focosi-cyber** [hivdb/covid-drdb-payload#1035]
https://covdb.stanford.edu/susceptibility-data/figure-epitope/

BEB epitope and escape mutations are depicted twice (top left and bottom right corners). Maybe you could replace with AZD3152

**Comment by KaimingTao** [comment]
@focosi-cyber, thanks for helping us fix the bug. I've replace the second BEB to BAM. We'll consider fully update the figure in the future including add the AZD3152.
