### ISSUE TITLE
[BUG] dioverti22-mab has a drug_name column instead of ab_name

### ISSUE THREAD

**Issue by by256** [hivdb/covid-drdb-payload#1040]
**Describe the error**

In all but one of the CSVs in `tables/rx_antibodies`, the column names are `["ref_name", "rx_name", "ab_name"]`.

In `tables/rx_antibodies/dioverti22-mab.csv`, there is a `drug_name` column instead of `ab_name`.

**To locate the error**

Look at the file `covid-drdb-payload/tables/rx_antibodies/dioverti22-mab.csv` and compare it to other files in `covid-drdb-payload/tables/rx_antibodies/`.

**Expected behavior**
`drug_name` should be renamed to `ab_name`.

**Comment by KaimingTao** [comment]
@by256 because these antibodies were treatment for patients so we call it drug name.

**Comment by KaimingTao** [comment]
@by256 my fault, the issue is being resolved, I'll release a new version today.
