### ISSUE TITLE
[BUG] Two mutations at the same position in BA.2 Spike:+N440Y and BA.2 Spike:+N440D entires in isolate_mutations.csv

### ISSUE THREAD

**Issue by by256** [hivdb/covid-drdb-payload#1048]
**Describe the error**

In two Omicron-mutant entries in isolate_mutations.csv, there are two mutations that appear in the same position.

**To locate the error**

In https://github.com/hivdb/covid-drdb-payload/blob/master/tables/isolate_mutations.csv

BA.2 Spike:+N440Y has two mutations at position 440:
Line 21808 - BA.2 Spike:+N440Y,S,440,Y,NULL,NULL
Line 21816 - BA.2 Spike:+N440Y,S,440,K,NULL,NULL

BA.2 Spike:+N440D has two mutations at position 440:
Line 21840 - BA.2 Spike:+N440D,S,440,D,NULL,NULL
Line 21848 - BA.2 Spike:+N440D,S,440,K,NULL,NULL

See the screenshots below.

**Expected behavior**

I believe the 440K mutations should be removed from these entries, as this is the usual mutation in BA.2 at position 440.

**Screenshots**

BA.2 Spike:+N440Y:
<img width="609" alt="image" src="https://github.com/hivdb/covid-drdb-payload/assets/44163664/1bbbaa16-4fa5-4439-8a4a-72fc72c44ed7">

BA.2 Spike:+N440D:
<img width="618" alt="image" src="https://github.com/hivdb/covid-drdb-payload/assets/44163664/ed41c1e7-562c-411b-923d-7d628027d51e">

**Comment by KaimingTao** [comment]
Hi @by256 , this bug is fixed.
