### ISSUE TITLE
New NEJM research letter

### ISSUE THREAD

**Issue by tonynick** [hivdb/covid-drdb-payload#109]
Important: check this list to see if we already have the paper: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/articles.csv

**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: 10.1056/NEJMc2119407
- PMID: [...]
- PMCID: [...]
- URL: [...]

**What topic studied by this paper should be add to our database? Please describe.**
This paper contains neutralization results of wild-type, Alpha, Beta, Gamma, Delta, and Omicron variants for etesevimab, bamlanivimab, imdevimab, casirivimab, tixagevimab, cilgavimab, sotrovimab, bamlanivimab-etesevimvab, casirivimab-imdevimab, tixagevimab-cilgavimab, remdesivir, molnupiravir, and nirmatrelvir.

**Which tables/figures contain the data?**
Table 1

**Additional information can help us entering this study faster. Attach files if necessary.**

- What's the neutralization assay(s) and where did you find it?
"live-virus focus reduction neutralization assay (FRNT)"
Paragraph 2
"we assessed the neutralizing activities of monoclonal antibodies against hCoV-19/Japan/NC928-2N/2021 (omicron; NC928), which was isolated from a traveler who arrived in Japan from Namibia; SARS-CoV-2/UT-NC002-1T/Human/2020/Tokyo (NC002), an early SARS-CoV-2 strain from February 2020; SARS-CoV-2/UT-HP127-1Nf/Human/2021/Tokyo (alpha; HP127); hCoV-19/USA/MD-HP01542/2021 (beta; HP01542); hCoV-19/Japan/TY7-503/2021 (gamma; TY7-503); and hCoV-19/USA/WI-UW-5250/2021 (delta; UW5250)."

"We validated the reactivity of all seven monoclonal antibodies by means of enzyme-linked immunosorbent assay (ELISA) coated with recombinant S protein derived from the early Wuhan reference strain, as well as from representative alpha, beta, gamma, and delta variants."
Paragraph 3

- Questions related to the potency / titer / fold data:
 "The individual monoclonal antibodies were tested at a starting concentration of 50,000 ng per milliliter as a 50% focus reduction neutralization titer. The monoclonal antibody combinations 
[nejm table 1 replication.xlsx](https://github.com/hivdb/covid-drdb-payload/files/7960079/nejm.table.1.replication.xlsx)
were tested at a starting concentration of 10,000 ng per milliliter for each antibody."
For the antivirals "In this category, the value is the 50% inhibitory concentration of the mean micromole value of triplicate reactions."
Both of the above are from the table 1 footnotes.

Last question: can you provide us the titer/IC50/fold data in tabular form (CSV/TSV/Excel)? You can upload the file here or provide the URL. We prefer individual titer/IC50 data rather than fold or median/mean titer/IC50.
[nejm table 1 replication.xlsx](https://github.com/hivdb/covid-drdb-payload/files/7960084/nejm.table.1.replication.xlsx)
[table1csvlong.csv](https://github.com/hivdb/covid-drdb-payload/files/7960087/table1csvlong.csv)

**Comment by KaimingTao** [comment]
@tonynick, thanks for creating this issue.
The paper is added in this commit: https://github.com/hivdb/covid-drdb-payload/commit/768d44af14ff1dcce8a5d6101bfa86697bd82c47.

**Comment by tonynick** [comment]
Awesome, thanks.
