### ISSUE TITLE
Time travel issue of Vicenti21

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#119]
Check infection date and isolation date of vicenti21-pth.csv

**Comment by philiptzou** [comment]
This is worth to have a validation case. Reopen until I finished the validation code.

**Comment by KaimingTao** [comment]
It's hard now because the breakthrough infection could be after vaccination of two-dose, even booster dose.

**Comment by philiptzou** [comment]
You are right. Another case is re-infection. Although the derived table script is not yet able to handle re-infection but we should allow them in raw data form right now.

**Comment by philiptzou** [comment]
Close to move the remaining issue to hivdb/covid-drdb#26
