### ISSUE TITLE
Displaying DMS data on website

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#12]
1. If a mutation is entered then show the results for a predefined list of antibodies. For example, 10 to 15 of the 25-30 antibodies in the DMS spreadsheet. Thus, we will only show the results for those antibodies that we know something about.
2. If an antibody is entered, there are potentially 4000 results. Therefore, we need a strategic way of showing the results. This can take 2 forms: I. limiting the number of mutations to those that have an escape fraction above a certain level (e.g., 0.1) and ii. not displaying the results in a table containing 1 row per results.

**Comment by philiptzou** [comment]
@rshaferw This ticket belongs to frontend development. It has been moved to hivdb/chiro-frontend#6.
