### ISSUE TITLE
Weigang21 should exclude Ivermectin as rx

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#120]
Also this paper is published.

**Comment by philiptzou** [comment]
The paper is published:

GISAID Accessions:
EPI_ISL_852709, EPI_ISL_852671, EPI_ISL_852667, EPI_ISL_852659, EPI_ISL_852809, EPI_ISL_852808, EPI_ISL_852805, EPI_ISL_852807, EPI_ISL_852806

**Comment by philiptzou** [comment]
SRA sequences are also available: https://www.ncbi.nlm.nih.gov/sra/?term=ERP132087

**Comment by KaimingTao** [comment]
should exclude Ivermectin as rx
