### ISSUE TITLE
Add Lee22 invivo data

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#121]
PMID: 34753749

**Comment by philiptzou** [comment]
Accession table:
[270247_2_supp_7519910_r29hmm.xlsx](https://github.com/hivdb/covid-drdb-payload/files/8018138/270247_2_supp_7519910_r29hmm.xlsx)

FASTA file:
[gisaid_hcov-19_2022_02_07_19.fas.txt](https://github.com/hivdb/covid-drdb-payload/files/8018153/gisaid_hcov-19_2022_02_07_19.fas.txt)

Mutation list:
[analysis-reports_1644262617037.zip](https://github.com/hivdb/covid-drdb-payload/files/8018162/analysis-reports_1644262617037.zip)

**Comment by KaimingTao** [comment]
@philiptzou I have several questions:

1. how to use `isolates.d` folder? Is it only for in vivo selection papers?
2. what dose `make psql-devdb` do?

**Comment by philiptzou** [comment]
@KaimingTao 

1. I created `isolate-mutations.d` and `isolates.d` folders. You can use these two like `rx_potency`, `rx_fold`. CSV files in those two folders will also be read into the PG database with the original `isolate-mutations.csv` and `isolates.csv`.
2. `make psql-devdb` start a psql console to direct access the PG database.
