### ISSUE TITLE
Monrad: There was just one sample. The mutation was found in a % of the reads. But we dont need to indicate that. 

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#125]
The study is Monrad.

**Comment by KaimingTao** [comment]
@rshaferw. Sorry, which paper do you refer to? Could you please share the DOI or nickname or author name?

**Comment by philiptzou** [comment]
Duplicate #116.

**Comment by philiptzou** [comment]
The severity=Hospitalized was updated by 75e76b4a1f18748c62253af123cedccd61a61016.
