### ISSUE TITLE
The isolates of Sabin21 should be examined and re-entered

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#127]
This is the actual cause of hivdb/covid-drdb#24.

https://github.com/hivdb/covid-drdb-payload/blob/master/tables/subject_history/sabin21-pth.csv

For P2, P3, P4, P5 and P6, there is no baseline sequence at infection event. For P1 there is no addition mutations in "B.1.311 full genome" comparing to "hCoV-19/USA/WI-GMF-48798/2021". Therefore, it's impossible for script to derive any invivo mutations from the raw data.

**Comment by KaimingTao** [comment]
It's before the `Unknown variant` was created. Should I rename all "NULL" infections as "Unknown variant", because the infection variant was not clear from the paper?

**Comment by philiptzou** [comment]
@KaimingTao Do we even know what variants are infected? And did the paper report any mutation?

**Comment by philiptzou** [comment]
The paper is published at: https://doi.org/10.1016/j.diagmicrobio.2022.115656
