### ISSUE TITLE
Update the `subjects` table new column `immune_status`

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#130]
The column `immune_status` is recently added to table `subjects` (see hivdb/covid-drdb#20). We need to update our `tables/subjects.csv` to include `immune_status` for in-vivo selection data.

Subjects need to be updated: https://gist.github.com/philiptzou/43ea52b1a855cfc60145c2ba808e5a23

The list is created by query:

```sql
SELECT DISTINCT s.*, ri.note
FROM subjects s, ref_invivo ri
WHERE
  s.ref_name=ri.ref_name AND
  s.subject_name=ri.subject_name AND
  immune_status is null
```

**Comment by KaimingTao** [comment]
The column is removed.
