### ISSUE TITLE
Pommeret21 - 10.1016/j.annonc.2021.07.015

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#148]
It seems https://doi.org/10.3390/ijms23010029 has the individual data available for Pommeret21. We should probably use their data or just request data from the authors (Pommeret21).

**Comment by KaimingTao** [comment]
#471

**Comment by KaimingTao** [comment]
The data were mentioned in paragraph.

**Comment by KaimingTao** [comment]
https://github.com/hivdb/covid-drdb-payload/commit/65b7a4bd774a26d0e0e0f7fedf00a2aed7f913c0
