### ISSUE TITLE
N450K and FDA21c

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#169]
[The comment of N450K](https://covdb.stanford.edu/search-drdb/?dosage=2&dosage=3&host=human&mutations=S%3A450K) reports that it has 9-fold reduced cilgavimab susceptibility according to [FDA21c](https://www.fda.gov/media/154701/download). However, we are missing this reference from DRDB.

**Comment by philiptzou** [comment]
Same issue with [K444E](https://covdb.stanford.edu/search-drdb/?dosage=2&dosage=3&host=human&mutations=S%3A444E).

**Comment by KaimingTao** [comment]
These data are added in this commit, https://github.com/hivdb/covid-drdb-payload/tree/532d91904ebd5a6ea5f00d3f4dc22c0b42192ddb

**Comment by philiptzou** [comment]
Re-open due to mismatching source. The source should not be "page 15 paragraph 3", it should be "Section 'Antiviral Resistance' (page 16-17)".

**Comment by KaimingTao** [comment]
The newest version was published last month, https://www.fda.gov/media/154701/download. Currently, the data is from the version published in Dec 2021. It requires more work to double-check if the values were changed.

**Comment by KaimingTao** [comment]
This issue is updated. https://github.com/hivdb/covid-drdb-payload/commit/f709184f3c7814697d4c70c52b1549245b40b3d6
