### ISSUE TITLE
Why Pegu21's data are changed to aggregated from?

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#176]
https://github.com/hivdb/covid-drdb-payload/commit/84c1acb826a5c3fc63b70b1877face27896ff9ae

Also the date in `pegu21-plasma.csv` is completely wrong. I will fix the date now but please check why it was changed to aggregated form.

**Comment by KaimingTao** [comment]
Because the published version drastically changed the figure 4 in preprint version, that means all individual data need to be reentered.

**Comment by philiptzou** [comment]
@KaimingTao In this way, can we change this issue to "Pending" for a reminder that individual data should be entered eventually?

**Comment by KaimingTao** [comment]
In the future, we will enter aggregate data for plasma unless the paper provided individual data tables. We don't need to change the entered data of this study.
