### ISSUE TITLE
Enter selection data from FDA22

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#178]

**Comment by philiptzou** [comment]
@KaimingTao Can you post the URL of these FDA factsheets? Thank you.

**Comment by KaimingTao** [comment]
@philiptzou 
https://www.fda.gov/media/156152/download
https://www.fda.gov/media/154701/download

**Comment by philiptzou** [comment]
The three in vitro selected mutations for CIL from FDA21c (https://www.fda.gov/media/154701/download) was already entered.

**Comment by philiptzou** [comment]
FDA22 page 14 describes "*Preliminary analysis of treatment-emergent variants focused on changes at amino acid positions with known phenotypically confirmed bebtelovimab-associated variations (i.e., K444, V445, G446, and P499) in serial viral samples obtained in the BLAZE-4 (Arms 9-14) bebtelovimab Phase 2 Study.*"

This is concordant to the description from Westendorf21, "*Consistent with the structure of the RBD complex, selection using LY-CoV1404 identified potential susceptibility to some, but not all, substitutions at residues K444, V445, G446, and P499*". This finding closed #253.

FDA22 further describes "*Treatment-emergent substitutions detected at ≥15% or ≥50% allele fractions at these positions
included K444N, V445G, G446V, and P499H/R*". These five mutations were added as in vitro emergent mutations referred to FDA22.
