### ISSUE TITLE
Displaying data on website

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#18]
- [ ] Providing a summary of the tables at the top. For example, for VP (any) there are 4 categories - Individual Mutation; Ind Mut - Aggregate; Variant/mutation combination; Variant/mut combo - Aggregate. It would be useful to see a summary of these categories at the top - with # references; #results; # not shown - ? other things to show in top summary
- [ ] The downloadable datasheets are problematic because the numbers appear as text - and it is not easy to reformat using excel format. Perhaps the ">", "<" need to be in separate column. That would fix the problem.
- [ ]

**Comment by philiptzou** [comment]
@rshaferw This ticket belongs to the frontend development. I'll close it and move it to hivdb/chiro-frontend.

**Comment by philiptzou** [comment]
The second issue is the same issue of hivdb/sierra-frontend#1.
