### ISSUE TITLE
Lucas21 misclassified isolate containing E484K as B.1

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#20]
Lucas reference misclassifies >=1 sequence as B.1 even though it contains several well known spike mutations: B.1_MZ467989

**Comment by philiptzou** [comment]
@rshaferw @KaimingTao MZ467989 contains E484K, N501T and D614G. It shouldn't be classified as B.1 only no matter how PANGOLIN said. I suggest to use B.1/E484K to distinguish from B.1 without E484K.

**Comment by KaimingTao** [comment]
OK

**Comment by KaimingTao** [comment]
This issue is fixed.
