### ISSUE TITLE
Add Burel22, DOI: 10.1101/2022.03.21.22272673

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#219]
Table 1/2/S1 have GISAID sequences.

**Comment by philiptzou** [comment]
This study is a case report of recombination of two variants B.1.160 and Alpha. The data format is compatible by the database but we may not have a way to show it on our website. Change to pending for now.

**Comment by KaimingTao** [comment]
exclude recombination because it's not selection.
