### ISSUE TITLE
[TODO] Add a workflow to build db file on cloud

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#22]
https://github.com/hivdb/covid-drdb-payload/actions/new

Once it finished, this workflow should become a required step of any pull request.

**Comment by KaimingTao** [comment]
Sorry, one thing I don't understand. Why this is a bug?

**Comment by philiptzou** [comment]
@KaimingTao Forgot to edit the assignees and labels.

**Comment by KaimingTao** [comment]
I close this issue, as the first actions are already used.
