### ISSUE TITLE
Check if we can find sequences for Niyonkuru21, 10.1186/s12879-021-06429-5

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#221]
Not sure if multiples timepoint whole genome sequences are available. But worth a try.

**Comment by KaimingTao** [comment]
As a limitation, whole genome sequencing was only performed once during admission for both patients, and therefore potential mutations during hospitalization were not characterized.

**Comment by KaimingTao** [comment]
exclude, no in vivo selection sequencing was performed.
