### ISSUE TITLE
Add Furukawa22 -- 2022 -- 10.1101/2022.01.25.22269735

### ISSUE THREAD

**Issue by zachandfox** [hivdb/covid-drdb-payload#247]
https://www.medrxiv.org/content/10.1101/2022.01.25.22269735v2.full.pdf

**Comment by zachandfox** [comment]
@KaimingTao This paper has fold reduction comparisons For D614G, Alpha, Beta, Gamma, Delta against Omicron, as well as Alpha, Beta, Gamma, Delta against D614G. How is this encoded in furukawa22-fold.csv? Some folds are less-than (reductions), while others are greater than. Is this handled by `fold_cmp` or by the way we order the isolates under `control_iso_name` and `iso_name`?

**Comment by zachandfox** [comment]
As well, the fold reductions in 2B are between age groups, not isolates. How do I record this?

**Comment by zachandfox** [comment]
This paper also uses a neutralization antibody titer method called 100-tissue culture infectious dose (TCID)_50; is this a data type that we collect? It is odd to see all the `rx_potency` values resolving to powers of 2

**Comment by philiptzou** [comment]
> @KaimingTao @philiptzou This paper has fold reduction comparisons For D614G, Alpha, Beta, Gamma, Delta against Omicron, as well as Alpha, Beta, Gamma, Delta against D614G. How is this encoded in furukawa22-fold.csv? Some folds are less-than (reductions), while others are greater than. Is this handled by `fold_cmp` or by the way we order the isolates under `control_iso_name` and `iso_name`?

Yes you can enter the < and > into `fold_cmp`. Remind me to review the results when a pull request created.

Question: NT50 are not available, right?

**Comment by philiptzou** [comment]
> https://www.medrxiv.org/content/10.1101/2022.01.25.22269735v2.full.pdf

The fold change should only be compared between control and experiment isolates. Since this is aggregated data, one way is to have three `subject`s stands for the three groups. Then entering the data into `rx_potency` for each group and we compare each variant to D614G.

**Comment by philiptzou** [comment]
> This paper also uses a neutralization antibody titer method called 100-tissue culture infectious dose (TCID)_50; is this a data type that we collect? It is odd to see all the `rx_potency` values resolving to powers of 2

Where did you find the description of the TCID50? Anyway, this database doesn't record TCID50/Cell count.

**Comment by zachandfox** [comment]
> > This paper also uses a neutralization antibody titer method called 100-tissue culture infectious dose (TCID)_50; is this a data type that we collect? It is odd to see all the `rx_potency` values resolving to powers of 2
> 
> Where did you find the description of the TCID50? Anyway, this database doesn't record TCID50/Cell count.

In the paper:
> 113 The neutralization assay was performed using authentic viruses as recently
> 114 described. 34,35

In [reference 34](https://www.jmaj.jp/download.php?id=10.31662%2Fjmaj.2020-0094), under _Measurement of neutralizing activity against SARS-CoV-2_, page 3:
> A two-fold serial dilution
> of heat-inactivated (56°C, 30 min) serum was prepared using
> Dulbecco’s Modified Eagle’s Medium as the diluent and
> mixed with a **100 tissue culture infectious dose (TCID)50** of vi-
> rus and incubated at 37°C for 1 hr. After this incubation, the
> serum-virus mixture was added to Vero E6 (TMPRSS2) cells
> and incubated at 37°C for 3 days.

Although, the next sentence states:
> **The neutralizing antibody**
> **titer was determined as the highest serum dilution** that did not
> show any cytopathic effects by observation under a light mi-
> croscope.

I suppose this is also a question that I have about what exactly is an NT50? Is it the same method as a serum dilution? I've extracted data from papers before that record potency by powers of 2, but am not familiar enough to know if this case fits that same category.

**Comment by philiptzou** [comment]
> mixed with a **100 tissue culture infectious dose (TCID)50** of virus

This was before the incubation. The 100 TCID50 here is basically the volume of the initial virus that mixed with the diluted serum. As you pointed out, the neutralization titers (NTs) were determined after the incubation.

**Comment by KaimingTao** [comment]
@zachandfox @philiptzou, about what is NT50 (50% neutralizing titer), please check this small video. https://www.youtube.com/watch?v=Up4NpJL02i8. 

There're many different methods to know when the 50% virus inhibition is established. TCID50 is one of the methods. If you see TCID50, that means the researchers are calculating 50% neutralizing of the virus. Vaguely, TCID (tissue culture infectious dose) is calculated by statistically counting how many cells are killed by the virus, the key point is 50% cells are killed. You can see a simple sample here: https://www.youtube.com/watch?v=2QBC5vyk-Z8&t=78s.

So in this paper, we will record it as NT50.

**Comment by KaimingTao** [comment]
> > mixed with a **100 tissue culture infectious dose (TCID)50** of virus
> 
> This was before the incubation. The 100 TCID50 here is basically [the volume](https://www.researchgate.net/post/How_to_calculate_800_TCID50_from_TCID50) of the initial virus that mixed with the diluted serum. As you pointed out, the neutralization titers (NTs) were determined after the incubation.
> 
> Since the paper states that the titer was the highest dilution that didn't "show any cytopathic effects", sounds like NT100 to me. What do you think @KaimingTao.

@philiptzou @zachandfox Yes, since the Figure 1A says the **highest serum dilution**, that means 100% inhibition. So it's NT100. The method is very close to sVNT method, but we use NT100.

**Comment by zachandfox** [comment]
I think I understand, but you may want to double-check my results!
