### ISSUE TITLE
Update Westendorf 2021.04.30.442182v6 

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#253]
V6 version is updated at Mar 30 2022

**Comment by philiptzou** [comment]
It seems there are in vitro selection data exist in this study (or the FDA factsheet too). Please don't close this one until the selection data are entered.

**Comment by KaimingTao** [comment]
Omicron TVP23328, hCoV/EHC_C192811 C.10, not sure if it's BA.1

**Comment by philiptzou** [comment]
No need to enter the in vitro selection data from this paper. See #178 for reason.
