### ISSUE TITLE
New papers

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#26]
- Miyakawa K. 10.1093/jmcb/mjab050. Rapid detection of neutralizing antibodies to SARS-CoV-2 variants in
post-vaccination sera. Figures 1E to G. Pfizer vaccine vs. 7 variants. PV assay. Previously uninfected (Figures E and F). Just show post-vaccine time points. Figure G - previously vaccinated.  **Pending**, move to pending list
- [x] Uriu, K. Ineffective neutralization of the SARS-CoV-2 Mu variant by convalescent and vaccine sera. Figures 1B and C - Raw data in tables in the Appendix. Pfizer vaccine,

**Comment by rshaferw** [comment]
- [ ] Neutralization potency of monoclonal antibodies recognizing dominant and subdominant epitopes on SARS-CoV-2 Spike is impacted by the B.1.1.7 variant. 10.1016/j.immuni.2021.03.023. Keep in our list of studies to be added. This is an old study. The raw data are in the supplementary material or in the 31 page version of the paper (Figures 5 and 6).

**Comment by rshaferw** [comment]
- [ ] Infection and mRNA-1273 vaccine antibodies neutralize SARS-CoV-2 UK variant. 10.1101/2021.02.02.21250799. This is an old study. It does not appear to have been published.

**Comment by rshaferw** [comment]
- [ ] Long-Term Evolution of SARS-CoV-2 in an Immunocompromised Patient with Non-Hodgkin Lymphoma. 10.1128/mSphere.00244-21. This belongs to in vivo selection category. We can put it on hold and discuss this one.

**Comment by rshaferw** [comment]
- [ ] A vaccine-induced public antibody protects against SARS-CoV-2 and emerging variants. Schmitz AJ. 10.1016/j.immuni.2021.08.013. Figure 1B has neutralization experiments. In vitro selection in the text "plaque assays on Vero cells with 2C08 in the overlay, purified the neutralization-resistant plaques, and sequenced the S genes (Figures S2A and S2B). Sequence analysis identified the S escape mutations G476D, G476S, G485D, F486P, F486V, and N487D"

**Comment by KaimingTao** [comment]
@rshaferw @philiptzou, Miyakawa Figure 1G is %inhibition, not titer or fold, which is currently not supported by the database. We should also think about how to show %inhibition on the web.

**Comment by KaimingTao** [comment]
> * [ ]  Infection and mRNA-1273 vaccine antibodies neutralize SARS-CoV-2 UK variant. 10.1101/2021.02.02.21250799. This is an old study. It does not appear to have been published.

It's published: Edara21,10.1001/jama.2021.4388
