### ISSUE TITLE
Check plasma outliers

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#287]

**Comment by KaimingTao** [comment]
@zachandfox please first check the outliers for WT/Omicron neutralizing titer and fold.

**Comment by zachandfox** [comment]
In [Aggarwal21](https://github.com/hivdb/covid-drdb-payload/blob/master/tables/rx_potency/aggarwal21-pot.csv#L198), the Omicron `rx_potency` values are below threshold and are recorded as 1's, whereas in the original paper they are null (see [Supplementary Tables from medRxiv](https://www.medrxiv.org/content/10.1101/2021.12.14.21267772v1.supplementary-material)). I expect many papers to follow this same pattern, wherein their below-threshold values are recorded as 1's.

**Comment by KaimingTao** [comment]
> 



> In [Aggarwal21](https://github.com/hivdb/covid-drdb-payload/blob/master/tables/rx_potency/aggarwal21-pot.csv#L198), the Omicron `rx_potency` values are below threshold and are recorded as 1's, whereas in the original paper they are null (see [Supplementary Tables from medRxiv](https://www.medrxiv.org/content/10.1101/2021.12.14.21267772v1.supplementary-material)). I expect many papers to follow this same pattern, wherein their below-threshold values are recorded as 1's. Would it not make sense to exclude instances where the `rx_potency` is less than the `potency_lower_limit`?

The potency values below the test threshold are treated differently between papers. Some of the papers treated the same as the threshold, some of them treated as 1, some of them treated as an estimated value.

If we ignore these values, the average value of potency will be biased by people who have enough antibodies. The challenge is how to represent them correctly.
