### ISSUE TITLE
What is WHO IS 20/136

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#296]
Is it a monoclonal antibody?

**Comment by KaimingTao** [comment]
@philiptzou it's the WHO international standard plasma sample. https://www.nibsc.org/documents/ifu/20-136.pdf

**Comment by philiptzou** [comment]
@KaimingTao Bob think it should belongs to CP. Since it is not a **monoclonal** antibody.

**Comment by KaimingTao** [comment]
We only have two records, I moved them to excluded folder for now.
