### ISSUE TITLE
Wang22e -- 10.1080/22221751.2022.2027219

### ISSUE THREAD

**Issue by zachandfox** [hivdb/covid-drdb-payload#307]
[Resistance of SARS-CoV-2 Omicron variant to convalescent and CoronaVac vaccine plasma](https://www.tandfonline.com/doi/full/10.1080/22221751.2022.2027219)

**Comment by zachandfox** [comment]
@KaimingTao CP plasma collected day of discharge from hospital (in Shanghai), from January-March 2020. The infection variant is not specified, but can we make an assumption on what it might be?

**Comment by KaimingTao** [comment]
@zachandfox use B.1
