### ISSUE TITLE
Isolates with partial mutation list shouldn't be assigned to a named variant

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#32]
Related to #31's second task.

Previously, if an isolate contains all important mutations (a.k.a. RBD/RBM mutations) of a named variant, we assign the named variant to it. However, this creates confusion when we need to distinguish isolates with only RBD mutations and isolates containing all Spike mutations.

**New rule: if an isolates contains only RBD/RBM mutations of a named variant, it shouldn't be classified as that variant. Only when all Spike mutations ± ≤3 non-important mutations can be assigned to the named variant.**

Please correct current `isolates.csv` table using the new rule, and follow the new rule in the future.

**Comment by KaimingTao** [comment]
@philiptzou for ± 3 non-important mutations do you mean spike mutations or non-spike mutations?

**Comment by philiptzou** [comment]
> @philiptzou for ± 3 non-important mutations do you mean spike mutations or non-spike mutations?
± 3 non-important Spike mutations

> How about a list of spike mutations or a variant missing one important mutation?
A different variant should be used. Ex. Alpha/E484K, Iota w/o E484K.

**Comment by philiptzou** [comment]
The commit 56781ca only fixed one variant. The clean-up is not yet done.
