### ISSUE TITLE
Goel study [BUG]

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#33]
**Describe the error**
Goel needs to be re-entered. It contains multiple errors. 10 patients had CP. The rest had VP-1 dose x 1M and VP-2 doses x 1M.

For CP, we will use month ranges: 1M, 2-6, >6

**Comment by KaimingTao** [comment]
@rshaferw according to page 11 right side. The table S4 contains all raw data, the Excel file is attached in zotero. The issue is we entered some vaccinees' data that contains pre-vaccine plasma data. I'll remove them because they're not infected.

**Comment by philiptzou** [comment]
@KaimingTao We should exclude the ~30 CP samples that from persons that are not previously infected. Also please add the source of the `timing` field to `section` field too. We couldn't find the timing data from table S4.

**Comment by KaimingTao** [comment]
> @KaimingTao We should exclude the ~30 CP samples that from persons that are not previously infected. Also please add the source of the `timing` field to `section` field too. We couldn't find the timing data from table S4.

I think what you mean timing is the timepoint? like T1, T2, T3, T4?

**Comment by KaimingTao** [comment]
> @KaimingTao We should exclude the ~30 CP samples that from persons that are not previously infected. Also please add the source of the `timing` field to `section` field too. We couldn't find the timing data from table S4.

Do you mean the `Days` column in the S4 table?

**Comment by KaimingTao** [comment]
This issue is being resolved. The `timing` is mentioned in the Table S4.
