### ISSUE TITLE
Bowen22 - 10.1126/science.abq0203

### ISSUE THREAD

**Issue by nparkin34** [hivdb/covid-drdb-payload#343]
working on this paper

**Comment by KaimingTao** [comment]
The mutation list in Table S1 has conflicts: Q498R shows in`BA.1` and `Both`.

2dose Sputnik V, demographics data is unknown
2dose Sputnik V + booster, demographics data is unknown.

**Comment by KaimingTao** [comment]
Preprint version: 10.1101/2022.03.15.484542 v1
