### ISSUE TITLE
Turelli - 10.1101/2022.07.28.501852

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#543]

**Comment by zachandfox** [comment]
The only immediately-accessible potency values come from table 2, which only has Omicron/BA.4 and Omicron/BA.5; the former will be the control_iso_name. 

In order to get potency values for additional isolates, we'd need to somehow extract them from a heat-map plot

**Comment by zachandfox** [comment]
@KaimingTao 
As well, are there additional steps for me to add `Omicron/BA.4 full genome` and `Omicron/BA.5 full genome` to the isolates table? This paper has the live virus isolates for each of them. They have provided the GIS id's, but I don't know if they necessarily represent the consensus required for the project.

**Comment by zachandfox** [comment]
Actually, I decided to use their iso_names as listed in GISAID: `hCoV-19/South Africa/CERI-KRISP-K040015/2022` and `hCoV-19/South Africa/CERI-KRISP-K040013/2022`

**Comment by KaimingTao** [comment]
@zachandfox please use the live virus in `SARS-CoV-2 live virus stocks`. I'm not sure if it's possible to get a bit accurate value from the heat map, I'll mark this issue as `revisit required`.

**Comment by rshaferw** [comment]
We will skip figure 1.
