### ISSUE TITLE
Barros-Martins J 2021

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#60]
**Describe the error**
I added a spreadsheet (supplementary materials) containing the raw data from Figure 1D. I think that the results appear basically consistent with the paper but I wasn't sure were the numbers of results are from. They differ from the paper. We can also use the spreadsheet to double check our results considering the fold resistances are so high and the titers for Beta and Gamma are extremely low. This may be in part because they use an sVNT which measures just RBD binding Abs.

**Comment by philiptzou** [comment]
I believe [the raw data](https://github.com/hivdb/covid-drdb-payload/blob/master/tables/rx_potency/barros-martins21-pot.csv) used the spreadsheet as its source, we should note this in the "section" column, @KaimingTao.

Unlike other study, such as Spencer21 (#59), Barros-Martins21 uses 0 to represent titer below threshold. This will cause zero-division issue when we trying to calculate the fold. Therefore the number was changed to 1, the minimal possible titer value.

I'll keep this issue open for now until the "section" column is updated.
