### ISSUE TITLE
Spike Y508H

### ISSUE THREAD

**Issue by focosi-cyber** [hivdb/covid-drdb-payload#621]
S:Y508H in the dropdown mutation menu should be Y505H

In outbreak there are only 50 Y508H censed worldwide.
I suppose several references were wrong at reporting Y508 and you copy-pasted it

**Comment by KaimingTao** [comment]
@focosi-cyber, thanks for raising the issue. I think you mean this page: https://covdb.stanford.edu/search-drdb/?mutations=S%3A508H.

I've checked these studies, they were using pseudotyped viruses, I think they were testing single mutations, not the actual virus isolates, also the purpose of these studies was to test potential resistance mutations, so they might be a bit different from the outbreak website.
