### ISSUE TITLE
Selection studies

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#63]
- [x] Avanzato, 10.1016/j.cell.2020.10.049
- [x] Baang, 10.1093/infdis/jiaa666
- [x] Bazykin, virological.org/t/580
- [x] Borges, 10.1128/mSphere.00244-21, Long-Term Evolution of SARS-CoV-2 in an Immunocompromised Patient with Non-Hodgkin Lymphoma. 10.1128/mSphere.00244-21. This belongs to in vivo selection category. We can put it on hold and discuss this one.
- [x] Bronstein, 10.1002/jmv.27445
- [x] Cele, 2021.09.14.21263564
- [x] Chen, 10.1128/mSphere.00480-21
- [x] Choi, 10.1056/NEJMc2031364
- [x] #72
- [ ] #137
- [x] Focosi, 10.3201/eid2710.211538
- [x] Gottlieb, 10.1001/jama.2021.0202
- [x] Guigon, 10.1016/j.jinf.2021.08.033
- [x] Hensley, 10.1093/cid/ciab072
- [x] Jensen, 10.1016/j.lanepe.2021.100164
- [x] Karim, 10.1101/2021.06.03.21258228
- [x] Kavanagh Williamson, 10.1101/2021.05.31.21257591 (contains NGS sequence)
- [x] Kemp, 10.1038/s41586-021-03291-y, 10.1101/2020.12.05.20241927
- [x] Khatamzas, 10.1101/2021.01.10.20248871
- [x] Lee, 10.1101/2021.08.25.21262417 (can't read mutation list)
- [x] Lohr, 10.1093/cid/ciab392
- [x] Mendes-Correa, 10.1101/2021.06.11.21257717
- [x] Monrad, 10.1093/ofid/ofab295
- [x] Nussenblatt, 10.1101/2021.10.02.21264267
- [x] Peiffer-Smadja, 10.3390/v13081642
- [x] Pommeret, 10.1016/j.annonc.2021.07.015
- [x] Sabin, 2021.10.02.21264415 (a chain of infection, household patients, all treated with BAM)
- [x] Schmitz, 10.1016/j.immuni.2021.08.013
- [x] Sepulcri, 10.1093/ofid/ofab217
- [x] Truffot, 10.3201/eid2710.211509
- [x] #139
- [x] #140
- [x] Weigang, 10.1038/s41467-021-26602-3, 10.1101/2021.04.30.21256244, please update

----
- [ ] Focosi21, 10.1101/2021.11.11.21266207 (a list of references)

**Comment by KaimingTao** [comment]
- [ ] Long-Term Evolution of SARS-CoV-2 in an Immunocompromised Patient with Non-Hodgkin Lymphoma. 10.1128/mSphere.00244-21. This belongs to in vivo selection category. We can put it on hold and discuss this one.

**Comment by philiptzou** [comment]
Close this issue since only one is left.
