### ISSUE TITLE
Add antibody neutralization studies

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#73]
- [x] Andrade, 10.1038/s41541-021-00384-7
- [x] Arora, 10.1038/s41423-021-00772-y
- [x] Aggarwal21,10.1101/2021.12.14.21267772 (exclude IgG because it's hard to know if it's from what kind of plasma)
- [x] Bates, 10.1001/jama.2021.11656
- [x] Basile, 10.1101/2021.12.12.472252 (need discussion)
- [x] Carreño21, 10.1016/j.ebiom.2021.103626
- [x] Cao21, 10.1101/2021.12.07.470392
- [x] Cameroni21,10.1101/2021.12.12.472269
- [x] Cele21b,10.1101/2021.09.14.21263564
- [x] Chen, 10.1016/j.celrep.2021.109604
- [x] Cho, 10.1038/s41586-021-04060-7
- [x] Choi21b,10.1038/s41591-021-01527-y
- [x] Collier, 10.1038/s41586-021-03739-1
- [x] Doria-Rose21,10.1101/2021.12.15.21267805
- [x] Drews, 10.1111/trf.16713
- [x] Dejnirattisai21b,10.1101/2021.12.10.21267534
- [x] Fabricius, 10.3390/vaccines9080918
- [x] Falsey, 10.1056/NEJMc2113468
- [x] Fenwick, 10.1016/j.celrep.2021.109814
- [x] Gidari, 10.1016/j.jinf.2021.07.019
- [x] Goel, 10.1126/science.abm0829
- [x] Gong, 2021.08.04.455140
- [x] Greaney, 2021.10.12.464114
- [x] Haslwanter, 10.1128/mBio.02473-21
- [x] Haveri, 10.1002/eji.202149535
- [x] Hayashi, 10.1101/2021.05.07.21256803, binding data and percent neutralizing antibody units data.
- [x] Kant21,10.1101/2021.08.06.21261716
- [x] Kitchin, 2021.11.08.21266049
- [x] Lassauniere21, 2021.11.08.21266075
- [x] Liu, 2021.09.13.460163
- [x] Liu21l,10.1101/2021.12.14.472719
- [x] Luke21,10.1101/2021.08.09.454215
- [x] Miyakawa, 2021.09.23.21264014
- [x] Miyakawa, 10.1093/jmcb/mjab050
- [x] Mishra21, 2021.10.04.463028
- [x] Moriyama, 10.1016/j.immuni.2021.06.015
- [x] Muller, 10.1016/j.jcv.2021.104912
- [x] Nadesalingam, 10.1016/S2666-5247(21)00157-9
- [x] Neumann.  Figure 4a (sVNT).
- [x] Neerukonda,2021.11.05.467523
- [x] Nemet21,10.1101/2021.12.13.21267670
- [x] Nguyen, 10.1093/infdis/jiab563
- [x] Nguyen, 10.1101/2021.07.22.21260942
- [x] Parry, 10.7554/eLife.69375
- [x] Planas21c,10.1101/2021.12.14.472630
- [x] Reincke, 2021.09.30.462420
- [x] Ren, 2021.09.03.458829
- [x] Roessler21,10.1101/2021.12.08.21267491
- [x] Scheid, 10.1016/j.cell.2021.04.032
- [x] Schmitz, 10.1016/j.immuni.2021.08.013
- [x] Schmidt21b,10.1101/2021.12.12.21267646
- [x] Stadtmueller, 2021.11.01.21265749
- [x] Suthar, 2021.09.30.462488
- [x] Thomson, 10.1016/j.cell.2021.01.037
- [x] Torres, 2021.09.28.462234
- [x] Vicenti, 10.3390/life11090896
- [x] Valleriani21, 10.3390/v13102011
- [x] VanBlargan21,10.1101/2021.12.15.472828 (Vero-TMPRSS2, Vero-hACE2-TMPRSS2)
- [x] Wang, 10.1016/j.lanwpc.2021.100276
- [x] Wang, 10.1038/s41541-021-00389-2
- [x] Wilhelm21b,10.1101/2021.12.07.21267432
- [x] Xie, 10.24272/j.issn.2095-8137.2021.343
- [x] Zhang21f, 10.1101/2021.05.15.21257254
- [x] Zhang21g,10.1080/22221751.2021.2017757
- [x] Zuckerman21b, 10.2807/1560-7917.ES.2021.26.45.2100974
- [x] Astrazeneca file
- [x] Lu, 10.1093/cid/ciab1041
- [x] Yu, 2021.12.17.21267961 
- [x] Zeng21b, 10.1101/2021.12.16.472934
- [x] Zeng, 10.1128/mBio.02510-21
- [x] Sheward, 2021.12.19.473354, excluded unknown vaccination samples
- [x] Syed, 2021.12.20.21268048
- [x] Dolzhikova,  2021.12.17.21267976
- [x] Meng, 2021.12.17.473248
- [x] Jacobsen, 2021.12.21.21267898
- [x] Carreno, 2021.12.20.21268134
- [x] Ai, 10.1080/22221751.2021.2022440
- [x] Zou, 2021.12.20.473584
- [x] Dejnirattisai21c,10.1101/2021.12.03.471045 (Figure 3F, unknown vaccine, dose, and time after vaccination)
- [x] Hoffmann, 10.1101/2021.12.12.472286
- [x] Edara, 2021.12.20.473557
- [x] Changrob21,10.1128/mBio.02975-21
- [x] Muik21b,10.1101/2021.12.22.21268103
- [x] Lusvarghi21,10.1101/2021.12.22.473880 (anonymous mAbs)
- [x] Arien21,10.1101/2021.12.23.21268316
- [x] Wang21k,10.1101/2021.12.24.474138
- [x] Zhou21e,10.1101/2021.12.27.474307
- [x] Touret21,10.1101/2022.01.01.474639
- [x] Meng21b,10.1101/2021.12.17.473248
- [x] Ikemura21, 10.1101/2021.12.13.21267761
- [x] Jacobsen21,10.1101/2021.12.21.21267898
- [x] Bekliz21,10.1101/2021.12.28.21268491
- [x] Boschi22,10.1101/2022.01.03.474769
- [x] Garcia-Beltran22,10.1016/j.cell.2021.12.033
- [x] Gruell21,10.1101/2021.12.14.21267769
- [x] Haveri21b,10.1101/2021.12.22.21268273
- [x] Hu21d,10.1101/2021.12.24.474110
- [x] Medigeshi22,10.1101/2022.01.04.22268747
- [x] Takashita22,10.1056/NEJMc2119407
- [x] Cui22,10.1016/j.cell.2022.01.019
- [x] Newman21,10.1101/2021.12.23.21268293

**Comment by philiptzou** [comment]
@KaimingTao Isn't "in Vitro" used for selection data? I checked severals in this list and they are not selection data. Where can I find a list of in Vitro selection data pending for entering? I thought we have one.

**Comment by KaimingTao** [comment]
"in vitro" is just mean not "in vivo" data. We can use neutralization to replace the title.

**Comment by KaimingTao** [comment]
> @KaimingTao Isn't the term "in Vitro" used for selection data? I checked several ones in this list and they are not selection data but mAb neutralization test (of course they are in vitro). Where can I find a list of in Vitro selection data pending for entering? I thought we have one.

"in vitro" is just mean not "in vivo" data. We can use neutralization to replace the title.

**Comment by KaimingTao** [comment]
> @KaimingTao Isn't the term "in Vitro" used for selection data? I checked several ones in this list and they are not selection data but mAb neutralization test (of course they are in vitro). Where can I find a list of in Vitro selection data pending for entering? I thought we have one.

Please check the OmicronPaper excel file to see which papers need to be entered. This list is for papers that are entered or decided to be entered but haven't been released.

**Comment by KaimingTao** [comment]
- [ ] Alidjinou, 10.1007/s15010-021-01732-4, Fig 1
- [ ] Alvarez-Diaz, 10.1016/j.virusres.2021.198629, Figure 2

**Comment by KaimingTao** [comment]
- [ ] Chen, 10.1101/2021.09.09.459504, Figure 1D-1I, Figure 2, Figure 4, Figure S4 (Breath index is the fold change)

**Comment by zachandfox** [comment]
Taking Assawakosri

**Comment by zachandfox** [comment]
@KaimingTao For Assawakosri22, what would the `control_iso_name` be if the study is making a comparison of vaccines' efficacies for delta against `BBIBP`, and then the same vaccines' efficacies for omicron against `BBIBP`?

**Comment by KaimingTao** [comment]
> @KaimingTao For Assawakosri22, what would the `control_iso_name` be if the study is making a comparison of vaccines' efficacies for delta against `BBIBP`, and then the same vaccines' efficacies for omicron against `BBIBP`?

This paper is special, the control is delta variant

**Comment by zachandfox** [comment]
Taking Banerjee22

**Comment by zachandfox** [comment]
Taking Chen22b [10.1080/22221751.2022.2035195](https://cogentoa.tandfonline.com/doi/pdf/10.1080/22221751.2022.2035195)

**Comment by zachandfox** [comment]
For Chen22b, how do I represent the fold data (figure 2) in the `rx_potency` table?

**Comment by zachandfox** [comment]
For Chen22b, the infection isolate is of lineage B.1.36.27, but we haven't that in the `isolates` table atm, how would I add it?

**Comment by KaimingTao** [comment]
> For Chen22b, how do I represent the fold data (figure 2) in the `rx_potency` table?

You can enter the data to rx_folder tables. I would update the document later, please check the rx_folder and use one file as an example.

**Comment by KaimingTao** [comment]
> For Chen22b, the infection isolate is of lineage B.1.36.27, but we haven't that in the `isolates` table atm, how would I add it?

Please check the document [Method: Variants, isolates and mutations](https://github.com/hivdb/covid-drdb-payload/wiki/Method:-Variants,-isolates-and-mutations) and [3.1.3 tables/variants.csv](https://github.com/hivdb/covid-drdb-payload/wiki/Entering-neutralization-data-(plasma)#313-tablesvariantscsv)

If you can get the GISAID or Genbank sequence you can recheck the variant name (lineage name) using our [Analysis program](https://covdb.stanford.edu/sierra/sars2/by-patterns/). If you want to know the mutations of the B.1.36.27, please check [outbreak.info](https://outbreak.info/situation-reports?pango=B.1.36.27).

**Comment by zachandfox** [comment]
> If you can get the GISAID or Genbank sequence you can recheck the variant name (lineage name) using our [Analysis program](https://covdb.stanford.edu/sierra/sars2/by-patterns/). If you want to know the mutations of the B.1.36.27, please check [outbreak.info](https://outbreak.info/situation-reports?pango=B.1.36.27).

The paper doesn't provide the GISAID, so I'm not able to check the variant/lineage name in the analysis program. 
Outbreak.info does provide the mutation list, so I should be able to add it to isolate_mutations.csv, but then I don't know what the name should be (`B.1.36.27 full genome`?). 

In the `variants.csv` table, what does the `consensus_availability` represent, and how do I find this?

If I understand correctly, what I need to do is add a variant to `variants.csv`, which implies that I must also add to `isolates.csv` and `isolate_mutations.csv`.

**Comment by KaimingTao** [comment]
> > If you can get the GISAID or Genbank sequence you can recheck the variant name (lineage name) using our [Analysis program](https://covdb.stanford.edu/sierra/sars2/by-patterns/). If you want to know the mutations of the B.1.36.27, please check [outbreak.info](https://outbreak.info/situation-reports?pango=B.1.36.27).
> 
> The paper doesn't provide the GISAID, so I'm not able to check the variant/lineage name in the analysis program. Outbreak.info does provide the mutation list, so I should be able to add it to isolate_mutations.csv, but then I don't know what the name should be (`B.1.36.27 full genome`?).
> 
> In the `variants.csv` table, what does the `consensus_availability` represent, and how do I find this?
> 
> If I understand correctly, what I need to do is add a variant to `variants.csv`, which implies that I must also add to `isolates.csv` and `isolate_mutations.csv`.

Yes, you're correct, the name would be B.1.36.27 full genome. It would be a reference for B.1.36.27.
`consensus_availability` please use `FALSE`, I will use program to automatically fetch the information later.

Yes, for a new variant, you need fill in three tables `variants`, `isolates`, and `isolate_mutations`

**Comment by zachandfox** [comment]
I'll take Cheng22

**Comment by zachandfox** [comment]
In Cheng22, is there anything particular to the PRNT50 neutralization titers that differentiates them from NT50 in other studies?

**Comment by zachandfox** [comment]
> > > If you can get the GISAID or Genbank sequence you can recheck the variant name (lineage name) using our [Analysis program](https://covdb.stanford.edu/sierra/sars2/by-patterns/). If you want to know the mutations of the B.1.36.27, please check [outbreak.info](https://outbreak.info/situation-reports?pango=B.1.36.27).
> > 
> > 
> > The paper doesn't provide the GISAID, so I'm not able to check the variant/lineage name in the analysis program. Outbreak.info does provide the mutation list, so I should be able to add it to isolate_mutations.csv, but then I don't know what the name should be (`B.1.36.27 full genome`?).
> > In the `variants.csv` table, what does the `consensus_availability` represent, and how do I find this?
> > If I understand correctly, what I need to do is add a variant to `variants.csv`, which implies that I must also add to `isolates.csv` and `isolate_mutations.csv`.
> 
> Yes, you're correct, the name would be B.1.36.27 full genome. It would be a reference for B.1.36.27. `consensus_availability` please use `FALSE`, I will use program to automatically fetch the information later.
> 
> Yes, for a new variant, you need fill in three tables `variants`, `isolates`, and `isolate_mutations`

For (B.1.36.27)[https://outbreak.info/situation-reports?pango=B.1.36.27], there are mutations in ORF1a, ORF1b, but these genes are not present in the (genes.csv)[https://github.com/hivdb/covid-drdb-payload/blob/master/tables/genes.csv] table. Is the genes.csv table subject to change, if so, how? If not, do I exclude the ORF1a, ORF1b mutations?

**Comment by zachandfox** [comment]
In Cheng22, there is a new isolate `hCoV-19/Hong Kong/VM20001061-2/2020` (gisaid 412028) that has a mutation list that is identical to an existing isolate, `hCoV-19/Hong Kong/HKU-001a/2020`, as shown below
```
hCoV-19/Hong Kong/HKU-001a/2020,S,367,F,NULL,NULL
hCoV-19/Hong Kong/HKU-001a/2020,ORF8,62,L,NULL,NULL
hCoV-19/Hong Kong/HKU-001a/2020,ORF8,84,S,NULL,NULL
...
hCoV-19/Hong Kong/VM20001061-2/2020,S,367,F,NULL,NULL
hCoV-19/Hong Kong/VM20001061-2/2020,ORF8,62,L,NULL,NULL
hCoV-19/Hong Kong/VM20001061-2/2020,ORF8,84,S,NULL,NULL
```
Does it still get added?

**Comment by zachandfox** [comment]
In Cheng22, sera is collected for infected individuals (pre-Omicron) but without a specified variant or date of infection, as quoted:

> We also evaluated sera from 
> the following groups of previously infected individuals: (1) indi-
> viduals 143–196 d postinfection who had recovered from COVID-
> 19 (pre-Omicron emergence) and had not yet received a vaccine
> (n = 30) 12 , (2) convalescent individuals with COVID-19 who had
> received one dose of BNT162b2 (n = 30) or (3) convalescent indi-
> viduals with COVID-19 who had received one dose of CoronaVac
> (n = 28)

In order to represent these subjects in cheng22-pth.csv, what would I use for their `iso_name` and their `event_date`?

**Comment by zachandfox** [comment]
I'll take Hu22 (10.1038/s41423-021-00836-z)

**Comment by zachandfox** [comment]
I'll take Kurahashi22 (10.1101/2022.02.24.22271262)

**Comment by KaimingTao** [comment]
10.3390/v14010144, Chatterjee22b

**Comment by KaimingTao** [comment]
Banerjee22, 10.1101/2022.01.13.475409

**Comment by zachandfox** [comment]
Taking Mannar22 (10.1126/science.abn7760)

**Comment by zachandfox** [comment]
For Mannar22, the Delta CP is specified as B.1.617.2 in the paper, but the B.1.617.2 variant is not listed in the variants.csv table, though B.1.617 is in the table. What should I use? Delta, or B.1.617.2?

**Comment by zachandfox** [comment]
The vaccine(s) for vaccinated patients is not provided in Mannar22, and there doesn't appear to be an "Unknown vaccine" in the vaccines.csv table. What should value should I use when filling out mannar22-vacc.csv?

**Comment by KaimingTao** [comment]
> For Mannar22, the Delta CP is specified as B.1.617.2 in the paper, but the B.1.617.2 variant is not listed in the variants.csv table, though B.1.617 is in the table. What should I use? Delta, or B.1.617.2?

Please use Delta as infected_var_name,  B.1.617.2 is Delta defaultly.

**Comment by KaimingTao** [comment]
> The vaccine(s) for vaccinated patients is not provided in Mannar22, and there doesn't appear to be an "Unknown vaccine" in the vaccines.csv table. What should value should I use when filling out mannar22-vacc.csv?

Please more all data to the excluded folder, if the vaccine is unknown. Please keep the file in the corresponding folders.

**Comment by zachandfox** [comment]
Taking Muik22 (10.1126/science.abn7591)

**Comment by zachandfox** [comment]
Taking Edara22 (10.1101/2022.01.24.22269189)

**Comment by zachandfox** [comment]
For Edara22, the researchers are based in the USA, but the sera were collected in India. Do I use India in the plasma and vaccine tables, or USA?

**Comment by philiptzou** [comment]
> For Edara22, the researchers are based in the USA, but the sera were collected in India. Do I use India in the plasma and vaccine tables, or USA?

I think for this case it should be India if they were collected in India.

**Comment by KaimingTao** [comment]
This issue is closed. In the future, all new studies will have its own issue number.
