### ISSUE TITLE
[New] Paper with neutralization data: 10.1126/science.abl6251 (Nabel, 2021)

### ISSUE THREAD

**Issue by MacGregorCox** [hivdb/covid-drdb-payload#77]
**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: [10.1126/science.abl6251 (2021)}

**What topic studied by this paper should be add to our database? Please describe.**

This paper contains the neutralisation results of many variants for both vaccines and monoclonal antibodies. Focusing on the response of antibodies to mutations emerging in immunocompromised patients.
Variants include: Alpha, Beta, Gamma, Delta, Eplsilon, Lambda etc, as well as constructed mutants based on variants emerging from immunocompromised patients 
Vaccines include: BNT162b2 ,mRNA-1273
paper also contains significant discussion of structural data. Especially the role of N-linked glycans in the evasion of mAbs.

**Which tables/figures contain the data?**
Variant mutation data: Fig1 A. 
neutralisation data: Fig2 A, B, Fig 3. FigS4. 

**Additional information can help us entering this study faster. Attach files if necessary.**

- What's the neutralization assay(s) and where did you find it? 
Monoclonal neutralisation assay details: 
      - IC50 - Fig2 text
      - VSV G pseudovirus - Supplementary materials page 10 
      - HEK293T w/ ACE2 - Supplemenary materials page 10.

- For vaccinee plasma/serum:
  - donor data is supplementary materials page 2

**Comment by philiptzou** [comment]
@MacGregorCox Thanks for suggesting this study (you are the first one who found this function!). We will take a look and will probably enter it soon.

**Comment by KaimingTao** [comment]
@MacGregorCox this paper is added to the database.
