### ISSUE TITLE
ORF9c currently can't be added in DRDB, the genes.csv is read-only

### ISSUE THREAD

**Issue by philiptzou** [hivdb/covid-drdb-payload#78]
The genes.csv must be identical to [Sierra-SARS2](https://github.com/hivdb/sierra-sars2/blob/master/src/main/resources/genes.json). For ORF9c, we either convert the mutation to an existing gene, or add such gene to Sierra-SARS2 if it's not fully covered by existing genes.

Anyway, we shouldn't just add genes to DRDB. The genes.csv should be a read-only table. Do not change it!

**Comment by KaimingTao** [comment]
It's known ORF9c (ORF14) would interfere with interferon from some paper. Although it's within N gene we may need to add it in the future.
