### ISSUE TITLE
Ma21, 10.1038/s41421-022-00381-7

### ISSUE THREAD

**Issue by MacGregorCox** [hivdb/covid-drdb-payload#81]
Important: check this list to see if we already have the paper: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/articles.csv

**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: [ https://doi.org/10.1101/2021.09.24.461616 ]

**What topic studied by this paper should be add to our database? Please describe.**
Neutralisation results of the 2G1 antibody against many VOCs 

**Which tables/figures contain the data?**
Fig 4. 

**Additional information can help us entering this study faster. Attach files if necessary.**

- What's the neutralization assay(s) and where did you find it?
  Pseudoviruses - see paragraph "2G1 neutralizing SARS-COV-2 varaints

- Questions related to the potency / titer / fold data:
  - What's the potency type and where did you find it?
IC50 is referenced in fig 4 

Last question: can you provide us the titer/IC50/fold data in tabular form (CSV/TSV/Excel)? You can upload the file here or provide the URL. We prefer individual titer/IC50 data rather than fold or median/mean titer/IC50.

**Comment by KaimingTao** [comment]
@MacGregorCox this paper is added to the database folder.

**Comment by KaimingTao** [comment]
Preprint: 10.1101/2021.09.24.461616

**Comment by KaimingTao** [comment]
Animal model, 2G1, beta delta variants
