### ISSUE TITLE
[New] Paper with mAb + sera neutralization results: 10.1101/2021.12.03.471045 (Dejnirattisai W, 2021c)

### ISSUE THREAD

**Issue by MacGregorCox** [hivdb/covid-drdb-payload#83]
Important: check this list to see if we already have the paper: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/articles.csv

**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: [https://doi.org/10.1101/2021.12.03.471045]
- PMID: [...]
- PMCID: [...]
- URL: [...]

**What topic studied by this paper should be add to our database? Please describe.**
The paper contains neutralisation results for many variants including Omicron against both mAb and sera. Many different mAbs are studies, including those that are therapeutically relevant, and many different kinds of sera, including vaccine sera and convalescent sera from many different VOCs.

**Which tables/figures contain the data?**
Sera neutralisation assays - Fig 3 
mAb neutralisation assays - Fig 4 and Table S1 

**Additional information can help us entering this study faster. Attach files if necessary.**
https://www.biorxiv.org/content/10.1101/2021.12.03.471045v2.full.pdf+html 
See supplimentary information on the BioRxiv page for this paper
-

**Comment by KaimingTao** [comment]
This paper is added.
