### ISSUE TITLE
[New] Paper with CP, VP and mAb neutralization results for Omicron variant: 10.1101/2021.12.12.472286 (Hoffmann M, 2021d)

### ISSUE THREAD

**Issue by MacGregorCox** [hivdb/covid-drdb-payload#85]
Important: check this list to see if we already have the paper: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/articles.csv

**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: [...]
- PMID: [...]
- PMCID: [...]
- URL: [https://www.biorxiv.org/content/10.1101/2021.12.12.472286v1.full]

**What topic studied by this paper should be add to our database? Please describe.**
This paper shows neutralisation results of Omicron variant for multiple mAbs, vaccine seras, and convalescent sera. 

**Which tables/figures contain the data?**
Fig 2 c - mAb neutralisation data
Fig 3 - Vaccine and Convalescent sera neutralisation data. 

**Additional information can help us entering this study faster. Attach files if necessary.**

- What's the neutralization assay(s) and where did you find it?
  Pseudovirus neutralisation assay as discussed in the methods section

- Questions related to the potency / titer / fold data:
  - NT50 is used for the sera neutralisation. Not clear what is used for the mAbs. 
   
demographic details related to the sera donors can be found in the supplementary materials.

**Comment by KaimingTao** [comment]
This paper is added.
