### ISSUE TITLE
Wang23x , 10.1101/2023.03.22.533805

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb-payload#858]

**Comment by zachandfox** [comment]
![image](https://user-images.githubusercontent.com/28547983/230247115-b3d61b34-e0be-4db5-81b9-22de04daf584.png)

@KaimingTao When adding new isolates, do we have a rule about adding  _a variant with its mutations_ or _a new variant altogether_ or _both_? 
For example, in this case, we have `DS.1` which is equivalent to `BA.2.75 Spike:R346T+F486S+F490S+K356T+R403K`, but I'm not sure if I should be adding one, the other, or both.

**Comment by KaimingTao** [comment]
@zachandfox You can use DS.1, but I recommend to use `BA.2.75 Spike:R346T+F486S+F490S+K356T+R403K` because DS.1 is not a well-known name. We can change the name when it's well-known.
