### ISSUE TITLE
Error in mutation position for BA.5.2.7 Spike in isolate_mutations.csv [BUG]

### ISSUE THREAD

**Issue by by256** [hivdb/covid-drdb-payload#909]
**Describe the error**

There seems to be an [error](https://github.com/hivdb/covid-drdb-payload/blob/1eed91dedca78588786b283ce30c64764fa68ffd/tables/isolate_mutations.csv#L19585) in the mutation positions for BA.5.2.7 Spike in [`isolate_mutations.csv`](https://github.com/hivdb/covid-drdb-payload/blob/1eed91dedca78588786b283ce30c64764fa68ffd/tables/isolate_mutations.csv#L19585).

Mutation 440K is followed by 440M, so the mutation at 440 is listed twice with two different resulting amino acids.

**To locate the error**

The error can be seen [here](https://github.com/hivdb/covid-drdb-payload/blob/1eed91dedca78588786b283ce30c64764fa68ffd/tables/isolate_mutations.csv#L19585), in `covid-drdb-payload/tables/isolate_mutations.csv`.

**Expected behavior**

Either 440M or 440K is incorrect, and the position in the incorrect one should be fixed.

I did some searching and found a [paper by Cao et al.](https://www.nature.com/articles/s41586-022-05644-7), where Extended Data Fig. 2 suggests that the mutation is actually K444M (see the row for BA.5.2.7).

I can update the value in `tables/isolate_mutations.csv` and create a pull request.

**Screenshots**

The following is a screenshot of `isolate_mutations.csv`. You can see that the position 440 is listed in two different rows, with different resulting amino acids.

<img width="481" alt="image" src="https://github.com/hivdb/covid-drdb-payload/assets/44163664/fb78213e-9e0b-43ad-95fa-1bffa2406acb">

**Comment by philiptzou** [comment]
@KaimingTao: Can you check this, it should be simple if it’s an error. Is
the position 440 a mixture position or not?

**Comment by KaimingTao** [comment]
@by256 , thanks for pointting out our errors. This issue is resolved in comit #ed152fb39a901bd9ae0e7a6a850e0371db01d00d, and is released now.
