### ISSUE TITLE
[New] Neutralisation study with mAb and vaccine sera data against multiple variants https://www.science.org/doi/10.1126/science.abl6251#F2 (Nabel et al, 2021)

### ISSUE THREAD

**Issue by MacGregorCox** [hivdb/covid-drdb-payload#91]
Important: check this list to see if we already have the paper: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/articles.csv

**What's the identifier of this new study? Please provide. (Just need one)**
- DOI: [...]
- PMID: [...]
- PMCID: [...]
- URL: [10.1126/science.abl6251]

**What topic studied by this paper should be add to our database? Please describe.**
This paper contains neutralisation results from multiple mAbs and Vaccine sera against multiple variants

**Which tables/figures contain the data?**
Fig 2 for both the mAb data, and the Vaccine Sera data. 

mAb results in IC50
Sera results in ID50. 

**Additional information can help us entering this study faster. Attach files if necessary.**

Please see the data that I have collected for this study attached. 
[Nabel et al (2021).xlsx](https://github.com/hivdb/covid-drdb-payload/files/7773931/Nabel.et.al.2021.xlsx)

**Comment by KaimingTao** [comment]
[add Nabel21,10.1126/science.abl6251, #77](https://github.com/hivdb/covid-drdb-payload/commit/666f2f7630c5b846a5233e0d1998c80386e5da6f)
