### ISSUE TITLE
See screenshot below 

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#93]
<img width="1372" alt="Screen Shot 2021-12-30 at 2 41 15 PM" src="https://user-images.githubusercontent.com/8672489/147792529-f9ee62cc-48f0-4515-98c0-3d428856accf.png">

**Comment by philiptzou** [comment]
@KaimingTao Please refresh the old database. @rshaferw I'll close this issue since it's not really a bug but just cause by unsynchronized data.

**Comment by KaimingTao** [comment]
The Dejnirattisai21b isn't listed by the crossref for a long time, if using API to get the information the result would be null.

**Comment by philiptzou** [comment]
OK so there's some delays when a very recent paper is added. We can do nothing for such case.
